version: '3.8'
## MYSQL config
services:
  mysql-demo:
    image: mysql:8.0.33
    container_name: mysql-demo
    ports:
      - "3305:3306"
    restart: always
    volumes:
      - /Users/duyphuong/Desktop/HaiNH/database/mysql/foodshopdemo:/var/lib/mysql
      - /Users/duyphuong/Desktop/HaiNH/Java/doantotnghiep/database:/docker-entrypoint-initdb.d
    networks:
      backend:
    environment:
      MYSQL_USER: hainh
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: WatchShop

## create network
networks:
  backend:
    name: foodshopdemo